name: docker-build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  lapis-archlinux-itchio:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: docker build
      run: docker build lapis-archlinux-itchio/
  lapis-archlinux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: docker build
      run: docker build lapis-archlinux/
